services:
  app-production:
    image: ghcr.io/zilusion/ambionity:latest
    container_name: ambionity-production
    restart: always
    ports:
      - '127.0.0.1:${PORT_PROD}:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL_PROD}
      - ORIGIN=${ORIGIN_PROD}
    volumes:
      - sqlite_data_prod:/app/.data

  app-edge:
    image: ghcr.io/zilusion/ambionity:edge
    container_name: ambionity-edge
    restart: always
    ports:
      - '127.0.0.1:${PORT_EDGE}:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL_EDGE}
      - ORIGIN=${ORIGIN_EDGE}
    volumes:
      - sqlite_data_edge:/app/.data

volumes:
  sqlite_data_prod:
  sqlite_data_edge:
